<a href="https://colab.research.google.com/github/RoozbehSanaei/PyTorch-TensorFlow/blob/gh-pages/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introductory Course to PyTorch and TensorFlow


Many data scientists and machine learning engineers frequently alternate between two main toolboxes: PyTorch and TensorFlow. Both in Python, These frameworks share many similarities, but also diverge in meaningful ways. These differences can make switching between the two frameworks cumbersome and inefficient. In this introductory course we try to learn Pytorch and Tensorflow in one go, In this way we not only hit two bird with one stone but also also understand the differences upfront, so we don't confuse only later on.




### *Load TensorFlow and PyTorch*

*TensorFlow*

In [16]:
import tensorflow as tf
print(f"tensorflow version: {tf.__version__}")

tensorflow version: 2.5.0


*PyTorch*

In [17]:
import torch
print(f"pytorch version: {torch.__version__}")

pytorch version: 1.9.0+cu102


## Tensors

### *Constant Tensors*

*TensorFlow*

In [24]:
tf_tensor = tf.constant([[1, 2],[3, 4],[5, 6]], dtype=tf.float16)
print(tf_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


*PyTorch*

In [25]:
torch_tensor = torch.HalfTensor([[1, 2],[3, 4],[5, 6]],device=torch.device('cpu'))
print(torch_tensor)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float16)


### *Random Tensors*

*TensorFlow*

In [26]:
tf_tensor =tf.random.uniform([4,4], minval=0, maxval=1, dtype=tf.float32, seed=1)
print(tf_tensor)

tf.Tensor(
[[0.4761244  0.809816   0.40282357 0.84008026]
 [0.5443208  0.30017078 0.5284884  0.0392561 ]
 [0.633996   0.4664613  0.4333365  0.12171769]
 [0.23395944 0.4864421  0.13252866 0.9327531 ]], shape=(4, 4), dtype=float32)


*PyTorch*

In [27]:
 torch_tensor = torch.rand(4,4,device=torch.device('cpu'),dtype=torch.float32)
 print(torch_tensor)

tensor([[0.0138, 0.5902, 0.9026, 0.8270],
        [0.3200, 0.7839, 0.0012, 0.1650],
        [0.9360, 0.3606, 0.2409, 0.3320],
        [0.3615, 0.8655, 0.4193, 0.9575]])


Tensors of different datatypes of can be created in PyTorch and TensorFlow


### *Assignment by Index*

*TensorFlow*

In [29]:
tf_tensor = tf.constant([[1, 2],[3, 4],[5, 6]], dtype=tf.float16)
tf_tensor[1,1] = 2

TypeError: ignored

*PyTorch*

## Variables and Parameters

*TensorFlow*

In [30]:
tf_variable = tf.Variable(tf_tensor)
tf_variable[1,1].assign(2)

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float16, numpy=
array([[1., 2.],
       [3., 2.],
       [5., 6.]], dtype=float16)>

*PyTorch*

In [32]:
torch_parameter = torch.nn.Parameter(torch_tensor)
with torch.no_grad():
  torch_parameter[1,1]=1
print(torch_parameter)

Parameter containing:
tensor([[0.0138, 0.5902, 0.9026, 0.8270],
        [0.3200, 1.0000, 0.0012, 0.1650],
        [0.9360, 0.3606, 0.2409, 0.3320],
        [0.3615, 0.8655, 0.4193, 0.9575]], requires_grad=True)


## Defining a new model

*TensorFlow*

In [35]:
class LinearRegressionKeras(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.w = tf.Variable(tf.random.uniform(shape=[1], minval=-0.1, maxval=0.1))
        self.b = tf.Variable(tf.random.uniform(shape=[1], minval=-0.1, maxval=0.1))

    def __call__(self,x): 
        return x * self.w + self.b

*PyTorch*

In [36]:
class LinearRegressionPyTorch(torch.nn.Module): 
  def __init__(self): 
    super().__init__()
    self.w = torch.nn.Parameter(torch.Tensor(1, 1).uniform_(-0.1, 0.1))
    self.b = torch.nn.Parameter(torch.Tensor(1).uniform_(-0.1, 0.1))
    
  def forward(self, x):  
    return x @ self.w + self.b

## Training Loop

*TensorFlow*

In [13]:
import numpy as np
def generate_data(m=0.1, b=0.3, n=200):
    x = np.random.uniform(-10, 10, n)
    noise = np.random.normal(0, 0.15, n)
    y = (m * x + b ) + noise
    return x.astype(np.float32), y.astype(np.float32)

x, y = generate_data()

In [14]:
x, y = generate_data()
tf_model_train_loop = LinearRegressionKeras()

optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate)

for epoch in range(epochs * 3):
    x_batch = tf.reshape(x, [200, 1])
    with tf.GradientTape() as tape:
        y_pred = tf_model_train_loop(x_batch)
        y_pred = tf.reshape(y_pred, [200])
        loss = tf.losses.mse(y_pred, y)
    
    grads = tape.gradient(loss, tf_model_train_loop.variables)
    
    optimizer.apply_gradients(grads_and_vars=zip(grads, tf_model_train_loop.variables))

    if epoch % 20 == 0:
        print(f"Epoch {epoch} : Loss {loss.numpy()}")

NameError: ignored

*PyTorch*

In [ ]:
class LinearRegressionPyTorch(torch.nn.Module): 
  def __init__(self): 
    super().__init__()
    self.w = torch.nn.Parameter(torch.Tensor(1, 1).uniform_(-0.1, 0.1))
    self.b = torch.nn.Parameter(torch.Tensor(1).uniform_(-0.1, 0.1))
    
  def forward(self, x):  
    return x @ self.w + self.b