<a href="https://colab.research.google.com/github/RoozbehSanaei/PyTorch-TensorFlow/blob/gh-pages/Copy_of_Tensor_Operations_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import torch

### Reshaping Tensors



#### *TensorFlow*

In [ ]:
tf_tensor = tf.constant([[1, 2],[3, 4],[5, 6]], dtype=tf.float16)
tf.reshape(tf_tensor, [2, 3])

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

#### *PyTorch*

In [ ]:
torch_tensor = torch.HalfTensor([[1, 2],[3, 4],[5, 6]],device=torch.device('cpu'))
torch_tensor.view(2,3)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

In [ ]:
torch_tensor = torch.HalfTensor([[1, 2],[3, 4],[5, 6]],device=torch.device('cpu'))
torch_tensor.view(-1,3)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

###  Tensor Elementwise Multiplication, Addition and Subtraction



#### *TensorFlow*

In [ ]:
tf_tensor1 = tf.constant([[1, 2],[3, 4],[5, 6]], dtype=tf.float16)
tf_tensor2 = tf.constant([[4, 3],[7, 1],[2, 4]], dtype=tf.float16)
print(tf_tensor1 * tf_tensor2)
print(tf_tensor1 + tf_tensor2)
print(tf_tensor1 - tf_tensor2)

tf.Tensor(
[[ 4.  6.]
 [21.  4.]
 [10. 24.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[ 5.  5.]
 [10.  5.]
 [ 7. 10.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[-3. -1.]
 [-4.  3.]
 [ 3.  2.]], shape=(3, 2), dtype=float16)


#### *PyTorch*

In [ ]:
torch_tensor1 = torch.HalfTensor([[1, 2],[3, 4],[5, 6]],device=torch.device('cpu'))
torch_tensor2 = torch.HalfTensor([[4, 3],[7, 1],[2, 4]],device=torch.device('cpu'))
print(torch_tensor1 * torch_tensor2)



tensor([[ 4.,  6.],
        [21.,  4.],
        [10., 24.]], dtype=torch.float16)

###  Tensor Multiplication



#### *TensorFlow*

In [ ]:
tf_tensor1 = tf.constant([[1, 2],[3, 4],[5, 6]], dtype=tf.float16)
tf_tensor2 = tf.constant([[4, 3, 7], [1 ,2, 4]], dtype=tf.float16)
print(tf_tensor1@tf_tensor2)
print(tf.matmul(tf_tensor1,tf_tensor2))

tf.Tensor(
[[ 6.  7. 15.]
 [16. 17. 37.]
 [26. 27. 59.]], shape=(3, 3), dtype=float16)
tf.Tensor(
[[ 6.  7. 15.]
 [16. 17. 37.]
 [26. 27. 59.]], shape=(3, 3), dtype=float16)


#### *PyTorch*

In [ ]:
torch_tensor1 = torch.HalfTensor([[1, 2],[3, 4],[5, 6]],device=torch.device('cpu'))
torch_tensor2 = torch.HalfTensor([[4, 3, 7], [1 ,2, 4]],device=torch.device('cpu'))
print(torch_tensor1 @ torch_tensor2)
print(torch.mm(torch_tensor1, torch_tensor2))
print(torch_tensor1.matmul(torch_tensor2))
print(torch_tensor1.mm(torch_tensor2))

###  Vector Dot Product



#### *TensorFlow*

In [ ]:
tf_tensor1 = tf.constant([1, 2, 3], dtype=tf.float16)
tf_tensor2 = tf.constant([4 ,5, 6], dtype=tf.float16)
tf.tensordot(tf_tensor1, tf_tensor2, 1)

<tf.Tensor: shape=(), dtype=float16, numpy=32.0>

#### *PyTorch*

In [ ]:
torch_tensor1 = torch.HalfTensor([1, 2, 3],device=torch.device('cpu'))
torch_tensor2 = torch.HalfTensor([4 ,5, 6],device=torch.device('cpu'))
print(torch.dot(torch_tensor1,torch_tensor2))

tensor(32., dtype=torch.float16)
