<a href="https://colab.research.google.com/github/RoozbehSanaei/PyTorch-TensorFlow/blob/gh-pages/Generating_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import tensorflow as tf
import torch
import tensorflow_probability as tfp


## Constant Tensors

#### *TensorFlow*

In [ ]:
tf_tensor = tf.constant([[1, 2],[3, 4],[5, 6]], dtype=tf.float16)

#### *PyTorch*

In [ ]:
torch_tensor = torch.HalfTensor([[1, 2],[3, 4],[5, 6]],device=torch.device('cpu'))

## Random Tensors

### Uniform Distribution

#### *TensorFlow*

In [ ]:
tf_tensor = tf.random.uniform([4,4], minval=0, maxval=1, dtype=tf.float32, seed=1)

#### *PyTorch*

In [ ]:
torch_tensor = torch.rand(4,4,device=torch.device('cpu'),dtype=torch.float32)

### Normal Distribution

#### *TensorFlow*

In [7]:
tf.random.normal([4,4], mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 1.2997719 , -0.30237177, -0.13434216,  0.33964786],
       [ 0.90262836,  1.5942805 , -1.1528667 , -4.4781594 ],
       [-2.88608   , -2.806104  ,  0.04099423, -1.0856115 ],
       [ 0.81831145,  2.8441727 ,  1.0848956 ,  3.0186584 ]],
      dtype=float32)>

#### *PyTorch*

In [11]:
torch.normal(mean = 2, std = 3, size=(4, 4),dtype=torch.float32)

tensor([[ 3.0225,  2.5156,  5.3459, -4.4868],
        [ 5.9280,  8.1764,  2.8973,  3.6830],
        [ 1.6894,  3.9443,  0.6622,  5.2258],
        [ 2.8127,  1.5566, -1.3875,  1.6875]])

In [17]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([0.8743, 3.4180, 3.1343, 2.8533, 5.7171, 6.3970, 6.8452, 7.8240, 9.3041,
        9.9654])

### Binomial Distribution



#### *TensorFlow*

In [55]:
tf.random.stateless_binomial(shape=[3], seed=[123, 1], counts=[10., 20.,30.0], probs= [0.8,0.5,0.9]).numpy()

array([10,  8, 27], dtype=int32)

#### *PyTorch*

In [49]:
from torch.distributions import Binomial
Binomial(torch.tensor([[10.,20,30.0]]), torch.tensor([0.5, 0.8,0.2])).sample()

tensor([[ 8., 18.,  3.]])

### Tensor DataTypes


### Bernoulli Distribution



#### *TensorFlow*

In [73]:
tfp.distributions.Bernoulli(probs=0.7).sample(sample_shape=(10,10))

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[0, 1, 1, 0, 1, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 0, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 1, 0, 1, 1],
       [1, 0, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 0, 1, 1, 0, 1, 0, 0]], dtype=int32)>

#### *PyTorch*

In [72]:
from torch.distributions import Bernoulli
Bernoulli(torch.tensor(0.7)).sample((10,10))

tensor([[1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 0., 1., 1., 1., 0., 1., 1., 0., 0.],
        [1., 0., 0., 1., 1., 1., 0., 1., 1., 1.],
        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
        [1., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 0., 0., 0., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
        [1., 1., 0., 0., 0., 1., 0., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

For different datatypes in TensorFlow see [here](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType)

For different datatypes in PyTorch see [here](https://pytorch.org/docs/stable/tensors.html)