<a href="https://colab.research.google.com/github/RoozbehSanaei/PyTorch-TensorFlow/blob/gh-pages/Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import torch
import tensorflow_probability as tfp
from torch import nn


## Sigmoid

#### *TensorFlow*

In [12]:
tf.keras.activations.sigmoid(tf.constant([[1, 2],[3, 4],[5, 6]],dtype=tf.float32))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7310586 , 0.8807971 ],
       [0.95257413, 0.98201376],
       [0.9933071 , 0.99752736]], dtype=float32)>

#### *PyTorch*

In [7]:
nn.Sigmoid()(torch.Tensor([[1, 2],[3, 4],[5, 6]]))

tensor([[0.7311, 0.8808],
        [0.9526, 0.9820],
        [0.9933, 0.9975]])


## Relu

#### *TensorFlow*

In [ ]:
tf.keras.activations.relu(tf.constant([[-1, 2],[3, 4],[-5, 6]],dtype=tf.float32))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 2.],
       [3., 4.],
       [0., 6.]], dtype=float32)>

#### *PyTorch*

In [ ]:
nn.ReLU()(torch.Tensor([[-1, 2],[3, 4],[5, -6]]))

tensor([[0., 2.],
        [3., 4.],
        [5., 0.]])


## Linear

#### *TensorFlow*

In [91]:
import numpy as np
model = tf.keras.Sequential([tf.keras.layers.Dense(2, activation=None,use_bias=False)])
model.build([0,2])
model.set_weights([np.array([[1,2 ],
        [ 3 , 4]]).transpose()])
model(tf.constant([[1, 2],[3, 4]],dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5., 11.],
       [11., 25.]], dtype=float32)>

#### *PyTorch*

In [92]:
model = nn.Linear(2, 2, bias=False)

with torch.no_grad():
    model.weight = nn.Parameter(torch.Tensor([[1, 2],[3, 4]]))

model(torch.Tensor([[1, 2],[3, 4]]))

tensor([[ 5., 11.],
        [11., 25.]], grad_fn=<MmBackward>)


## Convolution 1D

#### *TensorFlow*

In [228]:
import numpy as np
tf_inputs =  np.random.rand(1, 16, 1)
tf_weights = np.random.rand(3, 1, 4)


model = tf.keras.Sequential([tf.keras.layers.Conv1D(filters=4, kernel_size=3,use_bias=False)])
model.build(tf_inputs.shape)
model.set_weights([tf_weights])
tf.reduce_sum(model(tf_inputs))



<tf.Tensor: shape=(), dtype=float32, numpy=50.621925>

#### *PyTorch*

In [233]:

model = nn.Conv1d(in_channels=1, out_channels=4, kernel_size=3, bias=False)

model.weight = nn.Parameter(torch.Tensor(tf_weights).permute(2,1,0))
model(torch.Tensor(tf_inputs).permute(0,2,1)).sum()


tensor(50.6219, grad_fn=<SumBackward0>)


## Convolution 2D

#### *TensorFlow*

In [223]:
import numpy as np
tf_inputs =  np.random.rand(1, 16, 16, 1)
tf_weights = np.random.rand(3,3, 1, 4)


model = tf.keras.Sequential([tf.keras.layers.Conv2D(filters=4, kernel_size=3,use_bias=False)])
model.build(tf_inputs.shape)
model.set_weights([tf_weights])
tf.reduce_sum(model(tf_inputs))


<tf.Tensor: shape=(), dtype=float32, numpy=1706.0408>

#### *PyTorch*

In [224]:

model = nn.Conv2d(in_channels=1, out_channels=4, kernel_size=3, bias=False)

model.weight = nn.Parameter(torch.Tensor(tf_weights).permute(3,2,0,1))
model(torch.Tensor(tf_inputs).permute(0,3,1,2)).sum()

tensor(1706.0408, grad_fn=<SumBackward0>)