<a href="https://colab.research.google.com/github/RoozbehSanaei/PyTorch-TensorFlow/blob/gh-pages/Tensor_Operations_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import torch

###  Tensors Maximum and Maximum



#### *TensorFlow*

In [ ]:
tf_tensor = tf.constant([1,2,6,4,2,3], dtype=tf.float16)
print(tf.math.reduce_max(tf_tensor).numpy())
print(tf.math.reduce_min(tf_tensor).numpy())

6.0
1.0


#### *PyTorch*

In [ ]:
torch_tensor =  torch.tensor([1, 2, 6, 3, 4])
print(torch_tensor.max())
print(torch_tensor.min())

tensor(6)
tensor(1)


###  Trigonometric Functions



#### *TensorFlow*

In [34]:
tf_tensor = tf.constant([1,2,6,4,2,3], dtype=tf.float32)

print(tf.sin(tf_tensor).numpy())
print(tf.cos(tf_tensor).numpy())
print(tf.tan(tf_tensor).numpy())
print(tf.sinh(tf_tensor).numpy)
print(tf.cosh(tf_tensor).numpy)
print(tf.tanh(tf_tensor).numpy)


[ 0.84147096  0.9092974  -0.2794155  -0.7568025   0.9092974   0.14112   ]
[ 0.5403023  -0.41614684  0.96017027 -0.6536436  -0.41614684 -0.9899925 ]
[ 1.5574077  -2.1850398  -0.29100618  1.1578213  -2.1850398  -0.14254655]
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(6,), dtype=float32, numpy=
array([  1.1752012,   3.6268604, 201.71317  ,  27.289919 ,   3.6268604,
        10.017875 ], dtype=float32)>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(6,), dtype=float32, numpy=
array([  1.5430806,   3.7621958, 201.71564  ,  27.308231 ,   3.7621958,
        10.067662 ], dtype=float32)>>
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.7615942, 0.9640276, 0.9999876, 0.9993292, 0.9640276, 0.9950547],
      dtype=float32)>>


#### *PyTorch*

In [35]:
torch_tensor =  torch.tensor([1, 2, 6, 3, 4])
print(torch.sin(torch_tensor))
print(torch.cos(torch_tensor))
print(torch.tan(torch_tensor))
print(torch.sinh(torch_tensor))
print(torch.cosh(torch_tensor))
print(torch.tanh(torch_tensor))


tensor([ 0.8415,  0.9093, -0.2794,  0.1411, -0.7568])
tensor([ 0.5403, -0.4161,  0.9602, -0.9900, -0.6536])
tensor([ 1.5574, -2.1850, -0.2910, -0.1425,  1.1578])
tensor([  1.1752,   3.6269, 201.7132,  10.0179,  27.2899])
tensor([  1.5431,   3.7622, 201.7156,  10.0677,  27.3082])
tensor([0.7616, 0.9640, 1.0000, 0.9951, 0.9993])


#### *TensorFlow*

In [ ]:
tf_tensor1 = tf.constant([[1, 2],[3, 4],[5, 6]], dtype=tf.float16)
tf_tensor2 = tf.constant([[4, 3],[7, 1],[2, 4]], dtype=tf.float16)
print(tf_tensor1 * tf_tensor2)
print(tf_tensor1 + tf_tensor2)
print(tf_tensor1 - tf_tensor2)

tf.Tensor(
[[ 4.  6.]
 [21.  4.]
 [10. 24.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[ 5.  5.]
 [10.  5.]
 [ 7. 10.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[-3. -1.]
 [-4.  3.]
 [ 3.  2.]], shape=(3, 2), dtype=float16)


#### *PyTorch*

In [ ]:
torch_tensor1 = torch.HalfTensor([[1, 2],[3, 4],[5, 6]],device=torch.device('cpu'))
torch_tensor2 = torch.HalfTensor([[4, 3],[7, 1],[2, 4]],device=torch.device('cpu'))
print(torch_tensor1 * torch_tensor2)



tensor([[ 4.,  6.],
        [21.,  4.],
        [10., 24.]], dtype=torch.float16)

###  Slice of A matrix



#### *TensorFlow*

In [47]:
tf_tensor = tf.constant([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
tf_tensor[1:3,2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([23, 33], dtype=int32)>

#### *PyTorch*

In [48]:
torch_tensor = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
torch_tensor[1:3,2]

tensor([23, 33])

###  Sum, product and mean of a tensor



#### *TensorFlow*

In [66]:
tf_tensor = tf.constant([[11, 12], [13,14]],dtype=tf.float32)
print(tf.reduce_sum(tf_tensor))
print(tf.reduce_prod(tf_tensor))
print(tf.reduce_mean(tf_tensor))

tf.Tensor(50.0, shape=(), dtype=float32)
tf.Tensor(24024.0, shape=(), dtype=float32)
tf.Tensor(12.5, shape=(), dtype=float32)


#### *PyTorch*

In [64]:
torch_tensor = torch.tensor([[11, 12], [13,14]],dtype=torch.float32)
print(torch_tensor.sum())
print(torch_tensor.prod())
print(torch_tensor.mean())

tensor(50.)
tensor(24024.)
tensor(12.5000)
