<a href="https://colab.research.google.com/github/RoozbehSanaei/PyTorch-TensorFlow/blob/gh-pages/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import torch
import tensorflow_probability as tfp

### Reshaping Tensors



#### *TensorFlow*

In [ ]:
tf.reshape(tf.constant([[1, 2],[3, 4],[5, 6]], dtype=tf.float16), [2, 3])

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

#### *PyTorch*

In [ ]:
torch.HalfTensor([[1, 2],[3, 4],[5, 6]],device=torch.device('cpu'))

tensor([[1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 0., 1., 1., 1., 0., 1., 1., 0., 0.],
        [1., 0., 0., 1., 1., 1., 0., 1., 1., 1.],
        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
        [1., 0., 0., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 0., 0., 0., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
        [1., 1., 0., 0., 0., 1., 0., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

### Tensor DataTypes


For different datatypes in TensorFlow see [here](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType)

For different datatypes in PyTorch see [here](https://pytorch.org/docs/stable/tensors.html)